### PR TITLE
try tweaking some times to reduce flakiness

### PR DESCRIPTION
**Pull request by BinaryFissionGames**
Using this PR to try testing some changes to tests to reduce flakiness, since they don't seem to flake locally.

### CODE REVIEW

**Comment by BinaryFissionGames** [comment]
Ran 5 successful tests in a row; Empirically, using the tests cases exactly as the are from https://github.com/open-telemetry/opentelemetry-log-collection seems much more stable.

It's not 100% transparent to me why it's more stable, however.

**Review by dehaansa — APPROVED** [review]

**Review by cpheps — APPROVED** [review]
The fact that just tweaking time values makes it work is a bit of a code smell but I'm ok with this being a temporary mitigation.

**Review by cpheps — DISMISSED** [review]

**Comment by BinaryFissionGames** [comment]
https://github.com/observIQ/stanza/runs/5249699444 Another failure, on windows of course. I'll come back to this in a bit.

**Review by armstrmi — DISMISSED** [review]

**Comment by BinaryFissionGames** [comment]
@cpheps I looked into it a bit closer since I got some test failures locally at some point (some tests will actually deadlock if they fail by not polling a log entry fast enough, which confused me), and yeah, it's just generally hard to test these things better with how the file input operator is right now.

A future goal might be refactoring a bit and have this better testable, and rewriting some of these tests so they aren't so reliant on timeouts.

**Review by cpheps — APPROVED** [review]

**Review by armstrmi — APPROVED** [review]

**Pull request merged**
