### PR TITLE
Port move operator

### PR DESCRIPTION
**Pull request by Mrod1598**
## Description of Changes
Ported the move operator from the decomposition of the restructure operator discussed here: [OpenTelementry#68](https://github.com/open-telemetry/opentelemetry-log-collection/issues/68).
## **Please check that the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6896927|-0.17239773|123.38241|-0.22103882|
|1|5000|6.27609|+0.24150085|131.0555|-1.432785|
|1|10000|11.983028|-0.3276453|139.9336|-1.9124451|
|1|50000|56.966564|-2.691002|171.21283|-2.3384857|
|1|100000|115.17785|-4.7031937|230.91621|+8.348465|
|10|100|2.2931852|-0.2068851|126.77694|-1.3410568|
|10|500|7.1380424|+0.20683193|132.51132|-3.4482727|
|10|1000|14.241667|+0.51726913|145.0322|+1.3743286|
|10|5000|64.48432|+0.7760887|179.54526|-5.820175|
|10|10000|124.83807|-0.6789551|222.34294|-5.112335|

**Review by dehaansa — DISMISSED** [review]

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.5517352|+0.1206609|126.171875|+3.151802|
|1|5000|5.1725082|+0.1552062|129.84698|-0.28852844|
|1|10000|10.586347|+0.44818306|141.12595|+0.073410034|
|1|50000|50.89513|-0.070510864|172.79984|-0.8538513|
|1|100000|98.57804|+0.7035217|239.41527|+6.469284|
|10|100|2.0001428|+0.08626664|126.626884|-2.6445389|
|10|500|6.189605|-0.24148464|134.01535|-0.5035095|
|10|1000|11.879381|-0.051807404|140.10736|-0.8496704|
|10|5000|55.55091|+1.6192513|181.63753|+1.89534|
|10|10000|108.45961|+0.76921844|222.9666|-0.1328125|

**Comment by djaglowski** [comment]
We also need to add new operators to the `cmd/stanza/init_common.go` so they are available downstream.

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.5172887|+0.08618164|122.15127|-2.853714|
|1|5000|5.3448477|+0.051608086|132.87137|+1.1085663|
|1|10000|10.362301|-0.12059212|139.15746|-2.6821136|
|1|50000|50.82806|-0.49998093|172.592|+0.29040527|
|1|100000|101.893295|+1.4835052|232.38106|-13.170395|
|10|100|1.9310493|-0.034553766|130.06964|+2.015625|
|10|500|6.2757597|+0.13775826|136.36517|+2.8976288|
|10|1000|11.948484|+0.120495796|144.10533|+1.4711761|
|10|5000|55.395077|-1.3297653|180.95312|+1.2183533|
|10|10000|106.74349|+0.60201263|225.81883|+1.729126|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6379621|+0.20685506|125.017105|+0.012123108|
|1|5000|5.465448|+0.17220831|133.34564|+1.58284|
|1|10000|10.482828|-6.484985e-05|141.26132|-0.5782471|
|1|50000|49.845932|-1.4821091|173.16649|+0.8648987|
|1|100000|97.25072|-3.1590729|235.78934|-9.7621155|
|10|100|2.2242267|+0.2586236|130.48962|+2.435608|
|10|500|6.8449006|+0.70689917|140.9666|+7.499054|
|10|1000|12.344868|+0.5168791|142.90329|+0.26913452|
|10|5000|57.665676|+0.94083405|177.06735|-2.6674194|
|10|10000|107.669|+1.5275192|216.21376|-7.875946|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4827753|+0.051668286|124.441|-0.5639801|
|1|5000|5.5000677|+0.20682812|132.7003|+0.9375|
|1|10000|10.052075|-0.4308176|141.19073|-0.6488342|
|1|50000|51.082874|-0.24516678|169.91608|-2.3855133|
|1|100000|96.62141|-3.7883835|240.9371|-4.6143494|
|10|100|1.931141|-0.034462094|127.53152|-0.5224991|
|10|500|6.08616|-0.05184126|137.30927|+3.8417206|
|10|1000|12.172528|+0.34453964|138.75175|-3.8824005|
|10|5000|54.536083|-2.1887589|181.762|+2.0272217|
|10|10000|106.69159|+0.55010986|207.95973|-16.129974|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.517253|+0.086146|126.33028|+1.3252945|
|1|5000|5.189762|-0.10347748|127.98101|-3.7817917|
|1|10000|10.569065|+0.086172104|143.00485|+1.1652832|
|1|50000|49.068092|-2.2599487|170.65826|-1.6433258|
|1|100000|98.864044|-1.5457458|243.95811|-1.593338|
|10|100|1.9484065|-0.017196655|129.47832|+1.4243011|
|10|500|6.1034174|-0.034584045|137.02573|+3.5581818|
|10|1000|11.4829645|-0.3450241|141.2077|-1.4264526|
|10|5000|54.690918|-2.033924|178.2997|-1.4350739|
|10|10000|106.95044|+0.80895996|211.56937|-12.52034|

**Review by djaglowski — DISMISSED** [review]
LGTM. Let's update and see CI pass again, then can merge.

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6034663|+0.017249942|126.19868|+4.5790634|
|1|5000|5.4827476|+0.3963356|132.75404|-0.6598816|
|1|10000|10.344966|-0.08640003|140.10358|+0.29040527|
|1|50000|51.742706|+3.1385918|178.48398|+6.722931|
|1|100000|97.375404|+0.8279419|221.29283|-14.038116|
|10|100|1.9310741|-0.17242098|130.52196|+2.40477|
|10|500|6.1724687|+0.3619423|137.27249|+1.0841827|
|10|1000|12.207285|-0.06878853|143.43616|+1.6188049|
|10|5000|62.82934|+3.7740211|184.34024|+4.9027405|
|10|10000|109.46747|+0.01979065|230.09805|-1.1559906|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.5862423|+0.06896734|122.5136|-2.076645|
|1|5000|5.241459|+0|133.27896|+0|
|1|10000|10.275986|+0|140.65558|+0|
|1|50000|50.156326|+1.1244469|172.9841|+3.391159|
|1|100000|97.46698|-0.3278427|238.18413|-2.5128021|
|10|100|2.0344267|+0.1205703|127.43023|-2.729927|
|10|500|5.8450174|-0.22403193|138.14749|+1.5717926|
|10|1000|11.931208|+0|143.54068|+0|
|10|5000|54.19571|+0|177.1836|+0|
|10|10000|109.28677|+0|224.62743|+0|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4655311|-0.051743865|124.404366|-0.18588257|
|1|5000|5.1035805|+0|135.41325|+0|
|1|10000|11.086394|+0|139.64076|+0|
|1|50000|50.188362|+1.1564827|173.6149|+4.0219574|
|1|100000|96.31366|-1.481163|225.01886|-15.67807|
|10|100|1.8793383|-0.034518123|127.99946|-2.160698|
|10|500|5.9655585|-0.10349083|135.0004|-1.5753021|
|10|1000|11.638212|+0|141.63766|+0|
|10|5000|55.673115|+0|184.0163|+0|
|10|10000|109.93526|+0|222.97871|+0|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.7069343|+0.06900573|123.64898|-2.420662|
|1|5000|5.7068667|+0.7584629|132.7403|-3.5774536|
|1|10000|10.827789|+0.36223507|143.40033|+2.5382538|
|1|50000|50.362038|+2.4161758|173.83984|+3.607895|
|1|100000|100.10615|+5.3984756|235.64157|+2.2012482|
|10|100|1.9655377|-0.4483751|128.967|-0.9529877|
|10|500|5.6899443|-0.7241473|135.26132|-2.2091827|
|10|1000|11.293228|-0.586112|144.80739|+4.0229034|
|10|5000|55.796555|+7.120762|182.9569|+0.95285034|
|10|10000|108.3686|+1.9335632|219.98788|-2.3310852|

**Review by jsirianni — APPROVED** [review]

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4482796|-0.12066913|124.49354|-0.78245544|
|1|5000|5.37938|-0.10344696|132.92188|-1.4539337|
|1|10000|10.465633|-0.17259979|140.3327|-2.9105682|
|1|50000|51.36259|-0.8956413|172.00983|-1.0549622|
|1|100000|95.05556|-2.909935|223.15881|-3.6895142|
|10|100|1.9655609|-0.017257452|128.53125|-3.4125824|
|10|500|6.396711|+0.12077093|135.87689|+1.1002197|
|10|1000|12.069041|+0.017261505|141.3296|-3.8355408|
|10|5000|56.15531|+2.6285057|184.24596|+5.1608276|
|10|10000|109.346535|-9.241562|222.60709|-4.5072784|

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
