### PR TITLE
Goflow proto mapping

### PR DESCRIPTION
**Pull request by asenkowski**
## Description of Changes
Added in all IP protocols from https://en.wikipedia.org/wiki/List_of_IP_protocol_numbers. Used custom fields for 61, 68, 99, 114.

## **Please check that the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Add a changelog entry (for non-trivial bug fixes / features)
- [ ] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4310628|-0.034472108|129.4076|-0.97831726|
|1|5000|5.5863214|+0.65522385|137.69612|+0.16271973|
|1|10000|10.017304|-0.5173445|146.48895|+0.87257385|
|1|50000|53.501667|+5.1753616|175.19666|+1.3776855|
|1|100000|96.156105|-0.022224426|240.33136|+15.798355|
|10|100|1.9138075|+0.120753646|135.03139|+0.083114624|
|10|500|5.775892|-0.22421122|140.04364|-0.33580017|
|10|1000|12.00027|+0.32763672|146.37352|-3.55159|
|10|5000|53.775593|-0.48843002|174.23451|-3.3717651|
|10|10000|107.725716|+5.2453995|232.59523|+13.792435|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.362088|-0.10344696|125.618|-4.767914|
|1|5000|4.862164|-0.06893349|136.39655|-1.1368561|
|1|10000|10.017196|-0.5174532|146.36139|+0.7450104|
|1|50000|49.567425|+1.2411194|175.48639|+1.6674194|
|1|100000|95.92915|-0.24917603|231.49515|+6.962143|
|10|100|1.9482622|+0.15520835|134.6995|-0.2487793|
|10|500|5.8793144|-0.120788574|140.00768|-0.37176514|
|10|1000|11.413899|-0.25873375|147.19531|-2.7297974|
|10|5000|53.741642|-0.5223808|176.95016|-0.6561127|
|10|10000|102.16402|-0.31629944|234.10938|+15.30658|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4138533|-0.051681638|126.72616|-3.659752|
|1|5000|4.827677|-0.103420734|137.91568|+0.38227844|
|1|10000|9.895587|-0.6390619|144.24838|-1.3679962|
|1|50000|49.655643|+1.3293381|171.82852|-1.990448|
|1|100000|96.24366|+0.065330505|232.27007|+7.7370605|
|10|100|1.7930244|-2.9444695e-05|134.78421|-0.1640625|
|10|500|5.689719|-0.3103838|138.08122|-2.2982178|
|10|1000|11.672778|+0.0001449585|146.52411|-3.401001|
|10|5000|53.409782|-0.8542404|174.7104|-2.895874|
|10|10000|103.7262|+1.2458801|231.9868|+13.184006|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.46552|-1.4901161e-05|132.17296|+1.7870483|
|1|5000|5.0173926|+0.08629513|136.26993|-1.2634735|
|1|10000|10.517535|-0.017113686|144.7341|-0.88227844|
|1|50000|48.810345|+0.4840393|170.36934|-3.4496307|
|1|100000|96.96602|+0.7876892|235.132|+10.598999|
|10|100|1.8621223|+0.06906843|134.4274|-0.520874|
|10|500|5.8795323|-0.12057066|142.03812|+1.6586761|
|10|1000|11.413864|-0.25876904|146.50201|-3.4230957|
|10|5000|54.5425|+0.27847672|177.18669|-0.41958618|
|10|10000|103.325424|+0.84510803|224.33607|+5.5332794|

**Review by jsirianni — APPROVED** [review]
Thanks a lot 👍

**Pull request merged**
