### PR TITLE
Port retain operator

### PR DESCRIPTION
**Pull request by Mrod1598**
## Description of Changes
Ported the retain operator from the decomposition of the restructure operator discussed here: [OpenTelementry#68](https://github.com/open-telemetry/opentelemetry-log-collection/issues/68).
## **Please check that the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4310333|-7.379055e-05|124.71484|-0.29013824|
|1|5000|5.2413692|-0.051870346|133.30186|+1.5390625|
|1|10000|10.293281|-0.18961239|140.95514|-0.88442993|
|1|50000|51.48023|+0.15218735|172.6541|+0.35250854|
|1|100000|99.79531|-0.61447906|243.31345|-2.2380066|
|10|100|1.8621285|-0.10347462|130.97629|+2.9222717|
|10|500|6.0343437|-0.10365772|136.01334|+2.5457916|
|10|1000|12.034644|+0.2066555|143.2205|+0.5863495|
|10|5000|58.673065|+1.9482231|181.53543|+1.8006592|
|10|10000|103.428894|-2.7125854|220.66136|-3.4283447|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6724651|+0.24135804|124.845505|-0.15947723|
|1|5000|5.327697|+0.034457207|135.30887|+3.5460663|
|1|10000|10.776191|+0.29329777|142.72926|+0.8896942|
|1|50000|52.155575|+0.8275337|171.4103|-0.8912964|
|1|100000|96.691864|-3.717926|241.74649|-3.8049622|
|10|100|1.9828207|+0.017217636|129.17618|+1.1221619|
|10|500|5.9829297|-0.15507174|136.09079|+2.6232452|
|10|1000|11.810397|-0.017591476|142.22319|-0.41096497|
|10|5000|55.966858|-0.75798416|181.96565|+2.2308807|
|10|10000|111.48521|+5.343727|227.62271|+3.5330048|

**Review by jsirianni — CHANGES_REQUESTED** [review]
I think we should use the Open Telemetry license header for these changes.

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4483098|+0.10340321|126.06991|+2.3411942|
|1|5000|5.1551857|-0.1379633|135.44235|+2.5982056|
|1|10000|10.258976|-0.051649094|139.2174|+0.41123962|
|1|50000|52.019005|+1.2596588|170.82436|-2.6507263|
|1|100000|95.99844|-2.228485|236.5959|-3.286911|
|10|100|2.120768|+0.18972147|127.61355|-2.609108|
|10|500|6.2758584|-4.6253204e-05|137.40773|+0.9652405|
|10|1000|11.3450775|-0.89645576|141.79715|+0.6228485|
|10|5000|56.604164|+0.7224045|182.05441|-1.750412|
|10|10000|105.694046|-1.3022537|227.8296|+12.833237|

**Review by djaglowski — COMMENTED** [review]
Needs to be added to `init_common.go`

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6034962|+0.017279863|121.66285|+0.04323578|
|1|5000|5.327576|+0.24116421|132.6933|-0.72062683|
|1|10000|9.827938|-0.6034279|140.92377|+1.1105957|
|1|50000|48.621113|+0.016998291|168.6887|-3.072342|
|1|100000|100.43395|+3.8864899|242.17929|+6.848343|
|10|100|2.034558|-0.06893706|128.22656|+0.109375|
|10|500|6.344825|+0.5342984|134.69922|-1.48909|
|10|1000|13.017693|+0.7416191|143.46593|+1.6485748|
|10|5000|54.79368|-4.2616425|184.50175|+5.0642548|
|10|10000|109.87844|+0.43076324|231.7896|+0.535553|

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
