### PR TITLE
Independent buffer flusher

### LINKED ISSUE #148: Further decouple buffers and flushers
Currently, our flushers wrap a buffer, and handle reading and marking entries as flushed opaquely from the perspective of the output plugin. This is problematic when we need to retry because sometimes, the best way to build an output request is to mutate the entries given to the output to flush, so the second time we try, we have different entries than the first. 

To solve this, the output plugin should be responsible for reading from the buffer, then giving the flusher a retryable function. This way, the request can be constructed once (also saving some CPU cycles).

Additionally, this allows the output to handle partial retries. To facilitate this, the interface of buffers will need to change slightly to allow for marking a subset of the read entries as flushed. 

Here's a starting point for the design:

The `Flusher` interface is modified to look like this:
```go
type Flusher interface { 
  Do(func(context.Context) error) 
}
```

The flow would then be:
1) The output plugin calls Read() on its buffer in a loop
2) If any entries are returned, it does whatever processing necessary to turn it into a request (splitting into smaller chunks if necessary)
3) The output calls `flusher.Do(func(ctx context.Context) { client.Do(req) ... })`, which handles max concurrent flushers and retries. Since the retry step is after constructing the request, we don’t have to worry about having mutated the entries while constructing the request

### PR DESCRIPTION
**Pull request by camdencheek**
## Description of Changes

Makes flushers and buffers 100% independent. 
- Adds `buffer.ReadChunk(ctx)`, which uses new buffer configuration values `max_chunk_size` and `max_chunk_delay` to get a slice of entries from the buffer
- Replaces `FlushFunc` with `Clearer`, which is an object with methods `MarkAllAsFlushed` and `MarkRangeAsFlushed`, which allows for partial successes
- Changes the interface of `Flusher` to a simple `Flusher.Do(func(context.Context) error` pattern, which will run the passed closure concurrently (up to a limit) with other flushes. 

Fixes #148

This makes the output plugins slightly more complex in exchange for control over the process. Now, output plugins are responsible for:
1) Read a chunk from its buffer
2) Process that chunk into a request
3) Pass that request to `flusher.Do`, which handles concurrent execution and retry
4) Ensure that the `buffer.Clearer` is called in the passed function, signalling that the entries have been successfully flushed to disk

Why is this necessary?
- Previously, flushers and buffers were strongly intertwined. This meant you couldn't use one without the other. Some work previously went into reducing the dependency of buffers on flushers, but flushers still depended on buffers. This separates them completely. 
- Independence is necessary because in some cases, more flexible processing is needed before or after reading from the buffer. A driving example of this is when an API has a size limit. Previously, a chunk could only be marked as complete as a whole, but the addition of `MarkRangeAsFlushed` allows chunks to be split up after the fact (in the case that a payload is too large) or allow partial success (in the case that one of the entries fails to flush). 

Each of the outputs were tested for basic functionality. 

## **Please check that the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.8620961|+0.13791001|122.83688|-6.0929413|
|1|5000|6.2759743|+0.20688343|131.45164|-3.929016|
|1|10000|12.121019|-0.22418213|142.26064|-3.9569092|
|1|50000|59.052483|-1.8799515|171.05994|-4.930771|
|1|100000|118.08372|+3.0446243|229.77505|-10.003098|
|10|100|2.4656107|+0.13793802|127.12702|-5.2974167|
|10|500|7.2070885|+0.017302036|134.52626|-5.508896|
|10|1000|13.82825|-0.2754488|143.54486|-5.2016296|
|10|5000|65.4325|-4.8452454|188.86288|+4.0078125|
|10|10000|127.229355|+0.29660797|227.61356|+0.8589783|

**Review by djaglowski — CHANGES_REQUESTED** [review]
I'm not sure why this isn't failing on CI, but running `make vet` gives an error:
```
> make vet
GOOS=darwin /Applications/Xcode.app/Contents/Developer/usr/bin/make for-all CMD="go vet ./..."
# github.com/observiq/stanza/operator/builtin/output/otlp
./otlp.go:173:68: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
./otlp.go:176:68: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
make[1]: *** [for-all] Error 2
make: *** [vet] Error 2
```

Otherwise, this looks good to me. I'll test it out a bit more when this is fixed.

**Comment by camdencheek** [comment]
Interesting -- I don't get that error from `make vet`. I wonder if we're using different go versions. Looks like an actual issue though

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.7414111|+0.017225027|126.77627|-2.1535568|
|1|5000|6.1380587|+0.06896782|132.54121|-2.839447|
|1|10000|12.862546|+0.5173445|138.91473|-7.3028107|
|1|50000|61.462013|+0.52957916|180.44841|+4.4577026|
|1|100000|119.74426|+4.7051697|242.55994|+2.781784|
|10|100|2.3795264|+0.051853657|126.59092|-5.833519|
|10|500|7.827944|+0.63815737|133.3746|-6.660553|
|10|1000|13.241557|-0.8621416|141.80469|-6.941803|
|10|5000|64.51716|-5.7605896|180.44598|-4.409088|
|10|10000|127.8768|+0.94405365|224.96376|-1.7908173|

**Review by djaglowski — APPROVED** [review]

**Pull request merged**
