### PR TITLE
Debug logging

### PR DESCRIPTION
**Pull request by jsirianni**
## Description of Changes

- added debug logging to `journald_input`
- added debug logging to `google_output`

The goal is to provide optional logging for visualizing the lifecycle of an entry while using journald and Google output.

## **Please check that the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6724398|+0.20690751|127.85668|-1.619606|
|1|5000|5.4312825|+0.18987751|137.50229|+1.2782898|
|1|10000|10.241496|-0.017333984|142.41217|-4.297821|
|1|50000|52.208378|+4.3616333|176.70892|+5.8502197|
|1|100000|97.8767|-1.3118134|232.93669|+0.9255066|
|10|100|2.0173588|+0.08625376|133.1642|-0.29364014|
|10|500|6.017299|-0.017276764|142.69841|+3.2442017|
|10|1000|12.103709|+0.18989468|147.57947|-1.005661|
|10|5000|57.84578|+3.2476387|181.7135|+0.869751|
|10|10000|109.60346|+3.0864716|217.71889|-5.966324|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.7931563|+0.32762396|127.050644|-2.425644|
|1|5000|5.2759805|+0.034575462|138.90854|+2.6845398|
|1|10000|10.103399|-0.1554308|146.96686|+0.25686646|
|1|50000|52.173737|+4.326992|175.26791|+4.40921|
|1|100000|106.46417|+7.2756577|237.91945|+5.908264|
|10|100|2.1035013|+0.1723963|134.63753|+1.1796875|
|10|500|7.3103986|+1.2758226|141.44464|+1.9904327|
|10|1000|11.690015|-0.2237997|149.84576|+1.2606354|
|10|5000|55.93117|+1.3330307|180.31789|-0.52586365|
|10|10000|112.650375|+6.1333847|234.63187|+10.946655|

**Comment by jsirianni** [comment]
```json
{"level":"debug","ts":"2021-09-03T19:21:50.571Z","msg":"started journald with command: /usr/bin/journalctl --utc --output=json --no-pager --directory /var/log/journal --after-cursor s=0aecb59665c24d27a7b269922d58b9a8;i=41defb;b=e0e2b441131941ba9257002b8e2f6b9e;m=8916a970864;t=5cb1c360f4026;x=336f218c6b55326e","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.620Z","msg":"processing 1 entries","operator_id":"$.google_cloud_output","operator_type":"google_cloud_output"}
{"level":"debug","ts":"2021-09-03T19:21:50.620Z","msg":"sending 1 entries","operator_id":"$.google_cloud_output","operator_type":"google_cloud_output"}
{"level":"debug","ts":"2021-09-03T19:21:50.627Z","msg":"finished processing 0 entries from journald","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.627Z","msg":"stopping polling cycle","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.627Z","msg":"polling cycle finished","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.723Z","msg":"successfully sent %d entries","operator_id":"$.google_cloud_output","operator_type":"google_cloud_output"}
{"level":"debug","ts":"2021-09-03T19:21:50.771Z","msg":"started journald with command: /usr/bin/journalctl --utc --output=json --no-pager --directory /var/log/journal --after-cursor s=0aecb59665c24d27a7b269922d58b9a8;i=41defb;b=e0e2b441131941ba9257002b8e2f6b9e;m=8916a970864;t=5cb1c360f4026;x=336f218c6b55326e","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.829Z","msg":"finished processing 0 entries from journald","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.829Z","msg":"stopping polling cycle","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
{"level":"debug","ts":"2021-09-03T19:21:50.829Z","msg":"polling cycle finished","operator_id":"$.openshift.journald_input","operator_type":"journald_input"}
```

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4310598|-0.034472466|128.97939|-0.49690247|
|1|5000|5.138079|-0.103325844|136.44559|+0.22158813|
|1|10000|10.086286|-0.17254448|143.98627|-2.7237244|
|1|50000|50.966038|+3.1192932|175.56775|+4.7090454|
|1|100000|98.88303|-0.30548096|233.98222|+1.9710388|
|10|100|1.9828342|+0.051729202|134.68817|+1.2303314|
|10|500|6.7067223|+0.6721463|141.7403|+2.286087|
|10|1000|14.034798|+2.1209831|146.74704|-1.838089|
|10|5000|56.15363|+1.5554886|180.57732|-0.26643372|
|10|10000|109.56979|+3.052803|227.2174|+3.532196|

**Review by jmwilliams89 — DISMISSED** [review]

**Review by jmwilliams89 — APPROVED** [review]

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.448263|-0.017269254|129.34375|-0.13253784|
|1|5000|5.1379924|-0.10341263|136.8661|+0.6421051|
|1|10000|10.086226|-0.1726036|143.10251|-3.607483|
|1|50000|52.60404|+4.7572937|177.36314|+6.5044403|
|1|100000|100.20626|+1.017746|241.68063|+9.669449|
|10|100|2.2071102|+0.27600515|136.27533|+2.8174896|
|10|500|7.1726813|+1.1381054|139.38954|-0.06466675|
|10|1000|11.620953|-0.29286194|148.05145|-0.53367615|
|10|5000|56.41508|+1.8169403|179.62689|-1.2168579|
|10|10000|112.59927|+6.082283|231.92053|+8.235321|

**Pull request merged**
