### PR TITLE
Events example

### PR DESCRIPTION
**Pull request by jsirianni**
## Description of Changes

Added Kubernetes events example deployment

## **Please check that the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Add a changelog entry (for non-trivial bug fixes / features)
- [ ] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6552061|-0.034492373|123.74205|+0.5495682|
|1|5000|5.896771|-0.29315662|134.89023|+4.1511383|
|1|10000|12.207194|+0.6034584|139.56303|-1.8865814|
|1|50000|56.96685|-3.5163689|173.50053|-3.0040436|
|1|100000|110.50779|+6.1137314|219.45421|-6.3498077|
|10|100|2.448359|+0.13791394|128.39601|+1.7183456|
|10|500|6.948436|-0.8280015|135.34698|-0.01777649|
|10|1000|13.276243|-0.965559|142.4433|+0.16461182|
|10|5000|61.502407|-2.5688438|187.78798|+0.46577454|
|10|10000|123.55483|+5.8118515|220.04822|+7.9164886|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.8621126|+0.17241418|124.63847|+1.4459915|
|1|5000|5.224217|-0.96571064|131.48477|+0.74568176|
|1|10000|11.94854|+0.3448038|140.30577|-1.1438446|
|1|50000|59.79511|-0.68811035|171.41124|-5.093338|
|1|100000|114.364136|+9.9700775|236.17188|+10.367859|
|10|100|2.2414694|-0.06897569|129.39696|+2.7192917|
|10|500|6.862265|-0.9141722|131.49057|-3.8741913|
|10|1000|13.224468|-1.017334|139.5796|-2.6990814|
|10|5000|58.79711|-5.2741394|177.2372|-10.085007|
|10|10000|121.25516|+3.5121765|225.53152|+13.399796|

**Review by ericwholt — APPROVED** [review]
LGTM

**Review by djaglowski — COMMENTED** [review]
LGTM

**Pull request merged**
