### PR TITLE
Port copy operator

### PR DESCRIPTION
**Pull request by Mrod1598**
## Description of Changes
Ported the copy operator from the decomposition of the restructure operator discussed here: [OpenTelementry#68](https://github.com/open-telemetry/opentelemetry-log-collection/issues/68).
## **Please check that the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.517267|+0.086159945|123.46471|-1.5402756|
|1|5000|5.069|-0.22423983|132.36813|+0.6053314|
|1|10000|10.534681|+0.05178833|140.22589|-1.613678|
|1|50000|49.414505|-1.9135361|168.88281|-3.4187775|
|1|100000|101.15273|+0.7429428|244.03624|-1.515213|
|10|100|1.9137586|-0.051844478|130.04822|+1.9942017|
|10|500|6.310247|+0.1722455|135.76819|+2.300644|
|10|1000|11.603522|-0.22446632|141.71605|-0.9181061|
|10|5000|56.207355|-0.5174866|184.31479|+4.580017|
|10|10000|107.20577|+1.0642929|219.5594|-4.530304|

**Review by djaglowski — COMMENTED** [review]
Needs to be added to `init_common.go`

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.603458|-0.03447056|124.72832|-1.3413239|
|1|5000|5.482732|+0.534328|132.90881|-3.4089355|
|1|10000|10.63837|+0.17281532|137.19437|-3.6677094|
|1|50000|49.5695|+1.6236382|168.29944|-1.9325104|
|1|100000|99.822105|+5.1144333|239.09819|+5.6578674|
|10|100|1.9483058|-0.46560693|128.89629|-1.0236969|
|10|500|6.241528|-0.17256355|137.96983|+0.4993286|
|10|1000|11.741637|-0.13770294|142.53569|+1.7512054|
|10|5000|55.672974|+6.997181|182.1421|+0.13806152|
|10|10000|103.595825|-2.8392105|208.67525|-13.643723|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.7241694|+0.08624077|126.76899|+0.69934845|
|1|5000|5.396597|+0.44819307|132.60184|-3.7159119|
|1|10000|10.569178|+0.10362339|141.33513|+0.47305298|
|1|50000|51.05055|+3.1046867|172.44101|+2.2090607|
|1|100000|98.96789|+4.2602158|237.31007|+3.869751|
|10|100|1.9138293|-0.50008345|126.71094|-3.2090454|
|10|500|6.275981|-0.13811064|139.47374|+2.0032349|
|10|1000|12.431404|+0.55206394|141.49542|+0.7109375|
|10|5000|56.01252|+7.336727|181.04257|-0.96147156|
|10|10000|107.27504|+0.84000397|227.2411|+4.9221344|

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
