### PR TITLE
Flusher Timeout

### PR DESCRIPTION
**Pull request by djaglowski**
## Description of Changes
Flushers will now give up on retries eventually, rather than loop indefinitely.

## **Please check that the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Add a changelog entry (for non-trivial bug fixes / features)
- [ ] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6207151|-0.15518153|121.91406|-3.3883362|
|1|5000|5.8966613|+0.5172577|132.08554|-0.44961548|
|1|10000|11.845088|-0.06926155|137.6747|-3.3130493|
|1|50000|58.082504|-0.91091156|173.16069|-1.3729858|
|1|100000|120.01596|-1.491005|236.92712|+0.3980255|
|10|100|2.1896849|-0.051798582|129.4445|+1.9679413|
|10|500|6.603659|-0.22421837|135.60304|+0.5569763|
|10|1000|13.517593|+0.08629227|142.44302|-0.35775757|
|10|5000|66.55536|+3.9332542|185.09428|+0.45028687|
|10|10000|124.77439|+1.909584|222.77559|-8.259033|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6724414|-0.103455305|123.53677|-1.765625|
|1|5000|5.7932215|+0.41381788|130.63766|-1.8974915|
|1|10000|12.103717|+0.1893673|140.47656|-0.5111847|
|1|50000|59.20849|+0.21507263|176.14319|+1.6095123|
|1|100000|119.46975|-2.0372162|248.76091|+12.231812|
|10|100|2.206977|-0.03450656|128.68198|+1.2054138|
|10|500|7.0691833|+0.24130583|133.21902|-1.8270416|
|10|1000|13.362303|-0.06899834|142.02882|-0.7719574|
|10|5000|63.27707|+0.65496445|183.29459|-1.349411|
|10|10000|128.6564|+5.7915955|224.66096|-6.373657|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.5689859|-0.20691073|127.14588|+1.843483|
|1|5000|5.9138713|+0.5344677|133.38295|+0.8477936|
|1|10000|11.82789|-0.08645916|139.75957|-1.2281799|
|1|50000|58.06556|-0.92785645|174.41298|-0.12069702|
|1|100000|114.08411|-7.422859|229.27573|-7.253372|
|10|100|2.207068|-0.034415483|130.40881|+2.932251|
|10|500|7.017546|+0.18966866|134.50053|-0.5455322|
|10|1000|14.173044|+0.7417431|140.58284|-2.2179413|
|10|5000|61.704433|-0.9176712|184.15005|-0.49394226|
|10|10000|124.24815|+1.3833466|216.59038|-14.444244|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6034766|+0.051723838|123.59429|-1.7673721|
|1|1000|1.7069556|+0.15520275|122.65208|-2.709587|
|1|1000|1.7759018|+0.22414899|123.81735|-1.5443115|
|1|5000|6.017356|-0.034556866|133.11786|+1.4102936|
|1|5000|6.120821|+0.068908215|135.30469|+3.5971222|
|1|5000|6.327785|+0.27587223|131.29135|-0.416214|
|1|10000|11.879564|+0.24137211|143.4154|+1.4233551|
|1|10000|12.396989|+0.7587967|143.33876|+1.3467102|
|1|10000|12.276299|+0.6381073|137.72751|-4.2645416|
|1|50000|65.381485|+7.3901024|178.57071|+3.4188995|
|1|50000|59.555508|+1.5641251|175.70569|+0.5538788|
|1|50000|60.139835|+2.1484528|173.59052|-1.5612946|
|1|100000|113.946686|-2.6452484|227.9899|-0.0071411133|
|1|100000|114.49909|-2.092842|225.20595|-2.791092|
|1|100000|114.09986|-2.492073|224.73181|-3.2652283|
|10|100|2.3621767|+0.22416496|126.8156|-1.881607|
|10|100|2.2415233|+0.10351157|129.17336|+0.4761505|
|10|100|2.2414997|+0.10348797|129.29688|+0.5996704|
|10|500|6.6725407|-0.1896863|135.51657|+2.5235748|
|10|500|7.0518723|+0.18964529|133.13591|+0.14291382|
|10|500|6.7415013|-0.12072563|135.10196|+2.108963|
|10|1000|13.741721|+0.94839287|143.35587|-0.48397827|
|10|1000|13.414035|+0.62070656|142.83594|-1.0039062|
|10|1000|13.534715|+0.7413864|140.07893|-3.76091|
|10|5000|63.77737|+0.3435402|179.14224|-0.5960388|
|10|10000|124.411835|+3.9588547|221.67659|-2.2762604|
|10|10000|125.48176|+5.028778|223.55132|-0.40153503|
|10|10000|126.102806|+5.649826|234.72899|+10.776138|

**Review by andykellr — APPROVED** [review]

**Pull request merged**
