### PR TITLE
Make google cloud output split requests if they are too large

### PR DESCRIPTION
**Pull request by djaglowski**
resolves https://github.com/observIQ/stanza/issues/257

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.8793762|+0.15519285|120.378235|-3.743805|
|1|1000|1.6896852|-0.034498096|126.90975|+2.787712|
|1|5000|6.20698|+0.06894827|130.04526|-3.6340332|
|1|5000|6.069133|-0.068899155|131.47495|-2.2043457|
|1|10000|12.1209955|-0.20685768|139.77344|-0.4482727|
|1|10000|12.448619|+0.120765686|137.6681|-2.5536041|
|1|50000|61.4325|-2.43153|177.6351|+1.8359375|
|1|50000|63.242638|-0.6213913|177.23128|+1.4321136|
|1|100000|120.516655|+4.311363|236.70837|+12.622299|
|1|100000|119.38314|+3.1778488|221.30603|-2.7800446|
|10|100|2.465591|+0.13796115|122.3917|-4.579605|
|10|100|2.362262|+0.034632206|128.78772|+1.8164139|
|10|500|7.138121|-0.22416258|132.0132|-4.09375|
|10|500|7.914121|+0.55183744|132.60265|-3.504303|
|10|1000|13.3623905|-0.39644146|141.54916|-0.3798523|
|10|5000|64.03569|+0.2992592|180.88416|+2.2587585|
|10|5000|65.88061|+2.1441765|183.14171|+4.5163116|
|10|10000|125.79569|-1.1537476|217.18993|-10.706757|
|10|10000|125.93475|-1.0146866|226.76292|-1.1337585|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.8793484|+0.15516508|124.44774|+0.32569885|
|1|5000|6.569074|+0.4310422|132.93803|-0.7412567|
|1|10000|12.482988|+0.15513515|139.85965|-0.36206055|
|1|50000|59.757153|-4.1068764|176.33473|+0.53556824|
|1|100000|118.36555|+2.1602554|230.69559|+6.6095123|
|10|100|2.3449147|+0.01728487|128.44571|+1.4744034|
|10|500|7.500286|+0.1380024|138.7065|+2.5995483|
|10|1000|13.396839|-0.36199284|138.35184|-3.577179|
|10|5000|64.7081|+0.97166824|185.57382|+6.9484253|
|10|10000|136.8979|+9.948463|237.59227|+9.695587|

**Review by jsirianni — APPROVED** [review]
Looks great, and resolves the issue I was seeing in my environment.

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.9310892|+0.20690584|123.20407|-0.91796875|
|1|5000|6.3277926|+0.18976068|135.1906|+1.5113068|
|1|10000|13.15556|+0.82770634|140.23007|+0.008361816|
|1|50000|59.673717|-4.1903114|177.9437|+2.1445312|
|1|100000|123.60719|+7.4019012|232.4363|+8.35022|
|10|100|2.5345833|+0.20695353|128.32045|+1.349144|
|10|500|7.000205|-0.36207867|137.01671|+0.9097595|
|10|1000|14.293792|+0.5349598|140.04243|-1.8865814|
|10|5000|65.67377|+1.937336|182.38052|+3.755127|
|10|10000|127.6933|+0.74385834|215.9154|-11.981277|

**Comment by KonradSchieban** [comment]
👍  thanks, looks good!

**Comment by KonradSchieban** [comment]
What is the message that is being logged in the case a larger message has been split? Is there a way to find that out? @djaglowski @jsirianni

**Comment by jsirianni** [comment]
Large single messages are not being split. This is what we are doing:

- If bulk submission (multiple log entries) too big, split the bulk entries in half and retry. Continue doing this until all messages are submitted.
- If a single message is too big, replace it's record with the error given by the Google API. 

For example, I submitted a log entry that was well over the limit, the result in Cloud Logging looks like this:
Screen Shot 2021-04-05 at 3 09 55 PM

**Comment by KonradSchieban** [comment]
Thanks @jsirianni , this is what I was looking for!

**Pull request merged**
