### PR TITLE
Port add operator

### PR DESCRIPTION
**Pull request by Mrod1598**
## Description of Changes
Ported the add operator from the decomposition of the restructure operator discussed here: [OpenTelementry#68](https://github.com/open-telemetry/opentelemetry-log-collection/issues/68).
## **Please check that the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] Add a changelog entry (for non-trivial bug fixes / features)
- [x] CI passes

### CODE REVIEW

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.8448635|-0.017226934|125.39507|+1.791626|
|1|5000|6.4312744|+0.39668512|131.78516|-0.703125|
|1|10000|12.621516|+0.3108425|139.69693|-2.149109|
|1|50000|58.639935|-1.0176315|174.87486|+1.3235474|
|1|100000|118.81095|-1.0700912|234.34012|+11.772369|
|10|100|2.5000901|+1.9788742e-05|126.521286|-1.5967102|
|10|500|6.9830008|+0.051790237|133.57556|-2.3840332|
|10|1000|13.517734|-0.20666409|141.82018|-1.8376923|
|10|5000|62.588184|-1.1200485|179.63577|-5.72966|
|10|10000|126.41575|+0.8987198|208.58714|-18.868134|

**Review by djaglowski — COMMENTED** [review]
Needs to be added to `init_common.go`

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6034781|+0.017261744|125.61543|+3.995819|
|1|5000|6.0173345|+0.9309225|130.61409|-2.7998352|
|1|10000|11.862525|+1.431159|140.33675|+0.5235748|
|1|50000|57.62182|+9.017704|169.42241|-2.3386383|
|1|100000|117.58776|+21.040298|229.30522|-6.0257263|
|10|100|2.2414477|+0.13795257|126.74219|-1.375|
|10|500|7.086351|+1.2758245|134.05751|-2.1307983|
|10|1000|13.638414|+1.3623409|141.52223|-0.29512024|
|10|5000|64.638756|+5.583435|185.80374|+6.3662415|
|10|10000|124.888336|+15.440659|226.04163|-5.2124176|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.5517505|+0.01725018|125.01818|+0.5744858|
|1|5000|5.2414637|-0.0516634|134.99771|+3.0740814|
|1|10000|10.483155|+0.10378456|140.32503|-0.45959473|
|1|50000|50.017838|+0.84453964|170.651|-2.1811676|
|1|100000|106.98151|+6.0867615|250.04243|+8.749741|
|10|100|2.3275862|+0.31030464|129.50821|-0.6128845|
|10|500|6.793295|+0.3281188|135.46404|+0.57192993|
|10|1000|11.155419|-0.99994946|144.56102|+0.3684082|
|10|5000|56.292686|+0.9539337|179.5924|-1.8321686|
|10|10000|107.8608|+2.5307236|224.51562|+11.32045|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.4138553|-0.120645046|126.38672|+1.9430237|
|1|5000|5.1380534|-0.15507364|134.1079|+2.1842651|
|1|10000|10.327644|-0.05172634|141.5559|+0.77127075|
|1|50000|50.672863|+1.4995651|176.05698|+3.2248077|
|1|100000|97.31285|-3.581894|230.31102|-10.981674|
|10|100|1.9827762|-0.034505367|129.25876|-0.8623352|
|10|500|6.086333|-0.3788433|133.70663|-1.1854706|
|10|1000|12.172525|+0.017156601|142.07368|-2.118927|
|10|5000|54.743633|-0.5951195|179.45164|-1.9729309|
|10|10000|119.310295|+13.980217|230.42592|+17.230743|

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.6207192|-0.01720941|125.77168|-0.29795837|
|1|5000|5.0862684|+0.13786459|134.60048|-1.7172699|
|1|10000|9.965653|-0.49990082|140.0683|-0.79377747|
|1|50000|42.552353|-5.393509|167.55159|-2.680359|
|1|100000|99.41472|+4.7070465|234.25377|+0.81344604|
|10|100|2.0172875|-0.39662528|127.88443|-2.035553|
|10|500|6.086047|-0.3280444|135.80159|-1.6689148|
|10|1000|11.723697|-0.15564346|141.60251|+0.8180237|
|10|5000|55.228203|+6.55241|182.37001|+0.3659668|
|10|10000|107.89885|+1.4638138|223.34402|+1.0250549|

**Review by jsirianni — DISMISSED** [review]

**Comment by djaglowski** [comment]
| Log Files | Logs / Second | CPU Avg (%) | CPU Avg Δ (%) | Memory Avg (MB) | Memory Avg Δ (MB) |
| --- | --- | --- | --- | --- | --- |
|1|1000|1.5689971|+4.839897e-05|124.934|-0.34199524|
|1|5000|5.1724963|-0.31033087|132.62447|-1.7513428|
|1|10000|10.448215|-0.19001865|139.8059|-3.437378|
|1|50000|53.15655|+0.89831924|179.54027|+6.475479|
|1|100000|93.25741|-4.708084|231.25768|+4.4093475|
|10|100|2.000047|+0.017228603|128.66136|-3.2824707|
|10|500|6.1207094|-0.15523052|134.82246|+0.045791626|
|10|1000|11.931214|-0.120565414|141.7178|-3.447342|
|10|5000|55.31097|+1.7841644|178.59375|-0.49137878|
|10|10000|108.43295|-10.155144|222.1262|-4.988159|

**Review by jsirianni — APPROVED** [review]

**Pull request merged**
